# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f7da5667c01eeba49a9e3343dd4346fceb6907f322dd62f2f2cc3c63267850217a0d8e9df3fb2398b715e701ae4aea71a895a8d69557465c9d8e287be3fdf87c

test:
  secret_key_base: 401b5e7ee69b8b52434a85bff583ab86e50cf374fd3c461e7c334dba4111f95b2ccaa57526c3353c49a34e8b65a42950a78b919555d2d501ff846f59bc1be110

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
